# Config for SuperKaas plugin
## Location where new players will be teleported on first join
#
#spawn-location:
#  enabled: false       # Whether this feature is enabled
#  world: "world"       # The world name
#  x: 0                 # X coordinate
#  y: 999               # Y coordinate
#  z: 0                 # Z coordinate
#  yaw: 0.0             # Direction the player faces horizontally (0 = south)
#  pitch: 0.0           # Direction the player faces vertically (0 = straight ahead)
